# Multi-Container orchestration using Docker-Compose with default network for container communication
version: "3.8"
services:
  backend:
    build: ./node-server
    ports:
      - 5001:5001
    env_file:
      - ./node-server/.env
  frontend:
    build: ./react-server
    ports: 
      - 3000:3000
    depends_on:
      - backend
    stdin_open: true
    tty: true